### PR TITLE
Quick stab at implementing ETag

### PR DESCRIPTION
**Pull request by jeoffman**

### CODE REVIEW

**Comment by amccool** [comment]
Do you think we can add some negative tests for Etag failures?

**Comment by jeoffman** [comment]
I had to do something pretty hack-ish to make a strong unit test - I'm NOT proud of it.

**Comment by amccool** [comment]
thanks @jeoffman

**Comment by jeoffman** [comment]
LOL, what a difference 1 word can make....  I'm NOT proud of it.  😝

**Pull request merged**
